### ISSUE TITLE
メンター呼び出しランプのプラットフォーム

### ISSUE THREAD

**Issue by kentya6** [ait8/enpit-splash#12]
Slackにメンター呼び出しの通知が行ったら、BLE電球を光らせるようにしよう。

Web版とiOS版のどちらを開発しようかねー

iOSでプッシュ通知を受信したら光らせるというのでもありだね
SlackへのWebhookとプッシュ通知を連動させれば、後はiOSで光らせるプログラムの基盤は[ここ](https://github.com/kentya6/NexturnController)にあるので

**Comment by furuya-s** [comment]
Web側から呼び出しの通知をSlackとiOSに同時に送るって感じかね？

**Comment by shuyuhey** [comment]
そういうことなら全然実現できますよん

**Comment by kentya6** [comment]
同時に送る感じだね。

じゃあそれでやってみますか

電球光らせるのと同時にエレクトリカル・パレード流してもいいし

**Comment by shuyuhey** [comment]
デバイストークンを登録するAPI `POST /iostoken` とかにしときますか

**Comment by shuyuhey** [comment]
#17 PUSH通知周り
