### ISSUE TITLE
新しいUIの提案

### ISSUE THREAD

**Issue by shuyuhey** [ait8/enpit-splash#13]
キーワードはボタン押すだけという感じはどうだろう。
チーム名は一度選択したらCookieに保存されるとという感じです。

ボタンはぽよぽよしてると **カワイイ** よね

![img_1326](https://cloud.githubusercontent.com/assets/2537141/8740938/c30437fc-2c8c-11e5-8fcf-78e6435c1740.png)

そんでもって、一覧にないキーワードはその他をタップすると入力できると。
そうなると、キーワードは新規追加できるようにしたほうがいいのかなあ？MongoDBですかね。

**Comment by shuyuhey** [comment]
あと、基本的に使うユーザはスマホになりますかね？

**Comment by furuya-s** [comment]
チーム名保存はcookieなりLocalStorageなりでなんとか出来るでしょう。

キーワードをボタンだけにするのもいいかも。
「その他」を押したらpromptが表示されて、自由に文字列を入力して送信できるイメージでよい？
それとも新しくボタンが追加される感じ？

使うユーザに関しては、view側でPCでもタブレットでもスマホでも崩れずに見れるようなUIで作ろうと思ってるので制限はしないつもりです。
もし出来なかったらスマホ優先で。

**Comment by shuyuhey** [comment]
僕のイメージでは、プロンプト出てきて送信
1回送信したキーワードは次からボタンとして出てるみたいなのを想定してました

**Comment by furuya-s** [comment]
なるほど、じゃあ一回送信したキーワードはDB側にフィードバックして保存する方向で。
そうすると自分のチームが送信したキーワードのボタンがが別のチームでも出る感じ？

**Comment by shuyuhey** [comment]
そうなってくるかな。そうなると大量に出てきてしまって邪魔か？人気のキーワードでソートとかになるのかな？

**Comment by shuyuhey** [comment]
ついでに、DBの内容をリアルタイムでUIに反映するなら [socket.io](http://socket.io/) という手段もあるしノウハウもあります。

**Comment by furuya-s** [comment]
全部出すとしたら、よく使われてるキーワードを上に持ってきて、「その他」を埋もれないような位置に持ってこないといけなさそう。

自分で使ったキーワードをリアルタイムでやるならReact.js側でできるけど、DBの内容を持ってくるとなると確かにsocket.ioとかが必要になってくるかも。

とりあえず全部一気にやろうとするとパンクするので、１つずつやってこうと思います。

**Comment by shuyuhey** [comment]
それではひとまずサーバサイドはkeywordsを追加できるAPIを実装しておきます

**Comment by shuyuhey** [comment]
#16 とりあえずkeywordsを追加できるAPIは作った。

**Comment by furuya-s** [comment]
とりあえずチーム名もキーワードも選択式にしました。
どちらもAPIから引っ張ってきてます。
