### ISSUE TITLE
Team APIの仕様変更の提案

### ISSUE THREAD

**Issue by furuya-s** [ait8/enpit-splash#19]
どうせ名前しか返さないんだったら簡単化して配列だけにしたい
具体的には以下のような感じ
### Request

GET ./teams
### Response

["team1", "team2", "team3"]

**Comment by furuya-s** [comment]
ていうかチーム名くらい直打ちでいいかなあ。

**Comment by shuyuhey** [comment]
Cookieに残すならそれでもいい気がしてきたなあ。表記ゆれによってどれだけメンター側でわからなくなるかって感じ。

**Comment by furuya-s** [comment]
nameだったところをtextにすることで解決しました。

#20
