### ISSUE TITLE
コピーライト表示

### ISSUE THREAD

**Issue by furuya-s** [ait8/enpit-splash#25]
MIT Licenseだと著作権表示が必要ですが、著作者は誰にしましょう？

**Comment by shuyuhey** [comment]
おーマジか。団体ならenpitとか？

それかライセンス変えるかだけど、表示必要ないライセンスってあんのか？

**Comment by furuya-s** [comment]
http://qiita.com/tukiyo3/items/58b8b3f51e9dc8e96886
どのライセンスでも誰が著作者かは明確に書いておく必要があるようですね。
唯一パブリックドメインだけは表示しなくても大丈夫っぽい。
