### ISSUE TITLE
第1リリース

### ISSUE THREAD

**Issue by shuyuhey** [ait8/enpit-splash#27]
ぼちぼち機能が揃ってきてる気がするけど、どこまでやったらリリースにする？

あと残ってそうなのは、キーワードの新規追加とチーム名のクッキー保存ぐらい？

**Comment by furuya-s** [comment]
残ってる機能はそんなところですね。
あとはボタンを **ぽよぽよ** させたりUIを改善するくらい。

とりあえずその2つの機能作ったらリリースにしときます？

**Comment by ug23** [comment]
http://livedoor.4.blogimg.jp/yukkuri0616-picture/imgs/1/5/15dad73e.gif

**Comment by ug23** [comment]
![ざっかーばーぐ](http://livedoor.4.blogimg.jp/yukkuri0616-picture/imgs/1/5/15dad73e.gif)

**Comment by shuyuhey** [comment]
全部Doneかな？

**Comment by furuya-s** [comment]
機能は全部Doneしたので後はUIの調整と細かいところの修正ですね
