### ISSUE TITLE
他のAPIも実装しなきゃいけないかもしれない

### ISSUE THREAD

**Issue by shuyuhey** [ait8/enpit-splash#3]
Reactだと、例えばチーム一覧とかキーワード一覧APIもつくらなきゃいけない？
@furuya-s

**Comment by furuya-s** [comment]
あるに越したことはないけど、そんなに頻繁に変更しないんだったらjsonに直打ちでもいいかなぁ。

**Comment by furuya-s** [comment]
あーあったほうがベターですね。頻繁に変わらないようならば最悪jsxに直打ちでもいいけど。

**Comment by shuyuhey** [comment]
@furuya-s 実装してみた。片方Mergeしたらコンフリすると思う。

**Comment by furuya-s** [comment]
:+1: 
コンフリはこちらで直しておきます。
