### ISSUE TITLE
キーワード追加した時にわかりにくいかも？

### ISSUE THREAD

**Issue by shuyuhey** [ait8/enpit-splash#30]
![2015-07-22 11 27 11](https://cloud.githubusercontent.com/assets/2537141/8816640/a9007632-3064-11e5-92f7-ec90034ed291.png)

呼び出しまでできてる印象を受ける気がする

**Comment by furuya-s** [comment]
送信完了 → 追加完了 で大丈夫かな？
それとももっと別の表現にするか、そもそも追加と同時に送信するようにするか

**Comment by shuyuhey** [comment]
なかなか難しいな。
「追加したキーワードを選択して送信してください」ってメッセージ追加するのはどうかって思ったけど、見落としたらおしまいか。

**Comment by furuya-s** [comment]
とりあえず 送信完了 → 追加完了にして、注意書きを太字で書いてみました。これでどうでしょう
（XFDがあればメンターに送信されたかどうかはわかるかも）
#31
