### ISSUE TITLE
teams.jsonのメンバーに一部いらないものがあるかも？

### ISSUE THREAD

**Issue by shuyuhey** [ait8/enpit-splash#9]
https://github.com/ait8/enpit-splash/blob/master/config/teams.json.sample

`team.json`の`keywords`はいらないかも？かつての`mentors.json`からコピーミスかもしれない。

```
[
    {
        "name" : "",
        "keywords" : []
    }
]
```

**Comment by furuya-s** [comment]
teams.jsonってチーム名だけを入れておくやつだよね。
パパっと直しちゃいます。
